import json
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.preprocessing import StandardScaler

from features import FEATURE_COLUMNS


REPORT_DIR = Path("reports")
MODEL_PATH = Path("models/lr_model.pkl")
SCALER_PATH = Path("models/scaler.pkl")
SHAP_BACKGROUND_PATH = Path("models/shap_background.npy")


def evaluate_split(name, model, scaler, X_train, y_train, X_test, y_test):
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    y_prob = model.predict_proba(X_test_scaled)[:, 1]

    return {
        "name": name,
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "roc_auc": float(roc_auc_score(y_test, y_prob)),
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
        "classification_report": classification_report(y_test, y_pred, output_dict=True),
        "y_test": y_test,
        "y_prob": y_prob,
    }


def group_holdout_metrics(df):
    if "resume_path" not in df.columns:
        return None

    X = df[FEATURE_COLUMNS]
    y = df["label"]
    groups = df["resume_path"]
    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(splitter.split(X, y, groups))

    scaler = StandardScaler()
    model = LogisticRegression(class_weight="balanced", max_iter=1000, C=1.0, random_state=42)
    return evaluate_split(
        "resume_group_holdout",
        model,
        scaler,
        X.iloc[train_idx],
        y.iloc[train_idx],
        X.iloc[test_idx],
        y.iloc[test_idx],
    )


def write_report(df, row_metrics, group_metrics, model, scaler, dummy_acc):
    REPORT_DIR.mkdir(exist_ok=True)

    report = {
        "dataset": {
            "source": "data/silver_dataset.csv",
            "rows": int(len(df)),
            "label_counts": {str(k): int(v) for k, v in df["label"].value_counts().items()},
            "unique_resumes": int(df["resume_path"].nunique()) if "resume_path" in df.columns else None,
            "unique_jds": int(df["jd_path"].nunique()) if "jd_path" in df.columns else None,
            "feature_columns": FEATURE_COLUMNS,
            "feature_summary": df[FEATURE_COLUMNS].describe().round(4).to_dict(),
        },
        "baseline": {
            "dummy_most_frequent_accuracy": float(dummy_acc),
        },
        "row_split": {
            "accuracy": row_metrics["accuracy"],
            "roc_auc": row_metrics["roc_auc"],
            "confusion_matrix": row_metrics["confusion_matrix"],
            "classification_report": row_metrics["classification_report"],
        },
        "group_split": None,
        "model": {
            "type": "LogisticRegression",
            "class_weight": "balanced",
            "coefficients": {
                feature: float(coef)
                for feature, coef in zip(FEATURE_COLUMNS, model.coef_[0])
            },
            "intercept": float(model.intercept_[0]),
            "scaler_mean": {
                feature: float(value)
                for feature, value in zip(FEATURE_COLUMNS, scaler.mean_)
            },
            "scaler_scale": {
                feature: float(value)
                for feature, value in zip(FEATURE_COLUMNS, scaler.scale_)
            },
        },
        "limitations": [
            "Training labels are silver labels generated from matching heuristics, not real hiring decisions.",
            "Metrics measure agreement with silver labels and should not be presented as real-world hiring accuracy.",
            "External labeled resume/JD pairs should be reported separately because their label source differs.",
        ],
    }

    if group_metrics:
        report["group_split"] = {
            "accuracy": group_metrics["accuracy"],
            "roc_auc": group_metrics["roc_auc"],
            "confusion_matrix": group_metrics["confusion_matrix"],
            "classification_report": group_metrics["classification_report"],
        }

    (REPORT_DIR / "model_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Model Report",
        "",
        "## Scope",
        "",
        "This report evaluates the logistic regression model against `silver_dataset.csv`.",
        "The labels are silver labels generated by the project pipeline, not real hiring outcomes.",
        "",
        "## Dataset",
        "",
        f"- Rows: {report['dataset']['rows']}",
        f"- Label counts: {report['dataset']['label_counts']}",
        f"- Unique resumes: {report['dataset']['unique_resumes']}",
        f"- Unique JDs: {report['dataset']['unique_jds']}",
        f"- Features: {', '.join(FEATURE_COLUMNS)}",
        "",
        "## Metrics",
        "",
        f"- Dummy baseline accuracy: {dummy_acc:.4f}",
        f"- Row split accuracy: {row_metrics['accuracy']:.4f}",
        f"- Row split ROC-AUC: {row_metrics['roc_auc']:.4f}",
    ]

    if group_metrics:
        lines.extend(
            [
                f"- Resume-group holdout accuracy: {group_metrics['accuracy']:.4f}",
                f"- Resume-group holdout ROC-AUC: {group_metrics['roc_auc']:.4f}",
            ]
        )

    lines.extend(
        [
            "",
            "## Feature Coefficients",
            "",
        ]
    )
    for feature, coef in report["model"]["coefficients"].items():
        lines.append(f"- `{feature}`: {coef:.4f}")

    lines.extend(
        [
            "",
            "## Limitations",
            "",
            "- Training labels are silver labels generated from matching heuristics.",
            "- Metrics should be described as silver-label validation, not hiring accuracy.",
            "- External labeled pair validation is tracked separately.",
            "",
        ]
    )
    (REPORT_DIR / "model_report.md").write_text("\n".join(lines), encoding="utf-8")


def save_roc_curve(metrics):
    fpr, tpr, _ = roc_curve(metrics["y_test"], metrics["y_prob"])
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color="darkorange", lw=2, label=f"ROC curve (area = {metrics['roc_auc']:.4f})")
    plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("Receiver Operating Characteristic")
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.savefig("docs/roc_curve.png")
    plt.savefig(REPORT_DIR / "docs/roc_curve.png")
    plt.close()


def train_model():
    print("Loading silver dataset...")
    df = pd.read_csv("data/silver_dataset.csv")
    df.fillna(0, inplace=True)

    X = df[FEATURE_COLUMNS]
    y = df["label"]

    print("Splitting and scaling...")
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        stratify=y,
        random_state=42,
    )

    dummy = DummyClassifier(strategy="most_frequent")
    dummy.fit(X_train, y_train)
    dummy_acc = dummy.score(X_test, y_test)

    scaler = StandardScaler()
    model = LogisticRegression(class_weight="balanced", max_iter=1000, C=1.0, random_state=42)
    row_metrics = evaluate_split("row_split", model, scaler, X_train, y_train, X_test, y_test)

    print("\n--- ROW-SPLIT MODEL EVALUATION ---")
    print(f"Baseline dummy classifier accuracy: {dummy_acc:.4f}")
    print(f"Our model accuracy:                 {row_metrics['accuracy']:.4f}")
    print(f"ROC-AUC Score:                      {row_metrics['roc_auc']:.4f}")
    print("\nConfusion Matrix:")
    print(row_metrics["confusion_matrix"])

    print("\n--- FEATURE COEFFICIENTS ---")
    for fname, coef in zip(FEATURE_COLUMNS, model.coef_[0]):
        print(f"{fname:<25}: {coef:.4f}")

    group_metrics = group_holdout_metrics(df)
    if group_metrics:
        print("\n--- RESUME-GROUP HOLDOUT ---")
        print(f"Accuracy: {group_metrics['accuracy']:.4f}")
        print(f"ROC-AUC:  {group_metrics['roc_auc']:.4f}")
        print(f"Confusion Matrix: {group_metrics['confusion_matrix']}")

    joblib.dump(model, MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)
    
    import numpy as np
    X_test_scaled = scaler.transform(X_test)
    np.save(SHAP_BACKGROUND_PATH, X_test_scaled)
    
    save_roc_curve(row_metrics)
    write_report(df, row_metrics, group_metrics, model, scaler, dummy_acc)

    print("\nSaved lr_model.pkl, scaler.pkl, shap_background.npy, roc_curve.png, and reports/model_report.*")


if __name__ == "__main__":
    train_model()
